name: Haywire Kit PvP
version: 1.0.0
main: project.Core

commands:
  join:
  loadout:
    aliases: [loadouts]
  match:
  rank:
  message:
    aliases: [msg, w, whisper, tell]
  clearchat:
    aliases: [cc]
  gamemode:
    aliases: [gm]
  help:
  announce:
    aliases: [broadcast, announcement]
  mute:
    aliases: [silence]
  pixel:
    aliases: [pixels]
  rank2: